2024-07-23 21:25:59,002 | WARNING | Неверный тип данных для объекта Runner.
Traceback (most recent call last):
  File "C:\Users\Olesya\Urban University\module12\tests_12_4.py", line 79, in test_run
    chandler = Runner(10)
               ^^^^^^^^^^
  File "C:\Users\Olesya\Urban University\module12\tests_12_4.py", line 10, in __init__
    raise TypeError(f'Имя может быть только числом, передано {type(name).__name__}')
TypeError: Имя может быть только числом, передано int
2024-07-23 21:25:59,003 | WARNING | Неверная скорость для Runner.
Traceback (most recent call last):
  File "C:\Users\Olesya\Urban University\module12\tests_12_4.py", line 72, in test_walk
    joe = Runner('Joe', speed = -5)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olesya\Urban University\module12\tests_12_4.py", line 15, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -5
